// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwrswumrzswkeiwwoztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cnN3dW1yenN3a2Vpd3dvenRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NDM5NTEsImV4cCI6MjA1MjExOTk1MX0.cE3TvQ5sZxKTa0c8OSwBWKT0hLiCj7WDb81SdK09bVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);